### PR TITLE
Fixed the blank websites to block UI

### LINKED ISSUE #29: Edit blocked websites UI blank
# edit blocked websites interface blank

## Issue Description
After cloning the project, when you try to access the edit websites to block, it is a blank interface. As a result of this behavior, the extension is unable to block any websites

## Current Behavior
- The edit websites to block interface is blank

## Screenshots
Edit websites to block with a blank interface
*Caption: Blank UI after clicking edit websites to block*

## Possible Cause
There are code changes that are not in the main branch because the code in the deployed branch is different from the main branch

## Expected Behavior
- The edit websites to block should contain a list of default blocked sites and an input field to add your own sites

## Steps to Reproduce
  -Install the extension
  -Open the extension
  -Click the edit websites to block
  -Observe the blank UI with no default blocked websites and no input to add sites

## Additional Context
  -Chrome Version: [Version 126.0.6478.127 (Official Build) (64-bit)]
  -OS Version: [Windows 11 Home 23H2]

### PR DESCRIPTION
**Pull request by 02-ahmed**
When cloning the project on local machine, i noticed that the UI for editing the blocked websites was blank. This was because the some part of the code in the repository was different from the deployed code. This meant that the deployed version worked fine while the code in the repo was not working making it difficult to contribute.
I fixed it by replacing replacing those lines of code with the deployed code and that got it working again.
I also added a type for the default blocked sites to ensure type safety

Closes #29

### CODE REVIEW

File: my-extension/src/components/WebsiteEditPage.tsx [hunk 1]
```diff
@@ -17,23 +17,36 @@ export default function WebsiteEditPage() {
...
+      // If the app has been opened before, set to an empty array
+      setSlreadyBlockedWebsitesSet([]);
+      } else {
+      // If the app has not been opened before, use the hardcoded list and mark as opened
+      setSlreadyBlockedWebsitesSet(alreadyBlockedWebsites); // Assuming 'alreadyBlockedWebsites' is an array
+      setHasOpened(true); // This marks the initial setup as done
+      }
       }
-    }, []);
+      }, []); //this was different from the code in the deployment so copied the deployed code back which caused the edit websites to block to start working again
```
Comment (pritipsingh) [inline my-extension/src/components/WebsiteEditPage.tsx]: Please remove this comment. Rest looks good!

**Review by pritipsingh — CHANGES_REQUESTED** [review]

File: my-extension/src/components/WebsiteEditPage.tsx (hunk 1 above)
Comment (02-ahmed) [reply my-extension/src/components/WebsiteEditPage.tsx]: I've removed the comment
